# Generated by Django 4.2.4 on 2023-11-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humidityreading',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='temperaturereading',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='humidityreading',
            name='end_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='humidityreading',
            name='start_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='end_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='start_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
